### PR TITLE
Update filter

### LINKED ISSUE #4: Remove filter

### PR DESCRIPTION
**Pull request by treyyoder**
fixes #4 
* This is mostly code cleanup (Removing the filter, unused functions and CSS, renaming variables)

### CODE REVIEW

**Comment by sjmatta** [comment]
Please clean up linter issues (I'll add an issue to run the linter during continuous integration).

**Comment by treyyoder** [comment]
The linter issues have been fixed.

**Comment by sjmatta** [comment]
Please fix the typo on the commit. Thanks!

**Comment by treyyoder** [comment]
The typo is fixed.

**Pull request merged**
